#!/usr/bin/perl -w

my $HOME_DIR = $ENV{'HOME'};

# Get current tty number
my $cur_tty = `tty|sed -e 's/[^0-9]//g'`;
chomp $cur_tty;


# Get online ttys
my @online_ttys = `find /dev/ttys* -user \$USER | sed -e 's/[^0-9]//g' | grep -v -w $cur_tty`;
chomp @online_ttys;



# Load project table
my @ptable = `cat $HOME_DIR/.dirstack/prjtable.txt | sort -t ',' -k1n`;
chomp @ptable;



# Create online (prj#, tty#) table
my @online_table = ();

for (@ptable) {

    my ($pnum, $tty) = split(",", $_);

    if ( isMember($tty, \@online_ttys) ) {
        push @online_table, "$pnum,$tty";
    }
}


# Pick an offline prjnumber or create a new one 
my $cur_prjnum = GetPnum(@online_table);


# Create new dirstack if non existent
unless ( -e "$HOME_DIR/.dirstack/dirstack$cur_prjnum" ) {

    `echo \"UN\" >| $HOME_DIR/.dirstack/prjname$cur_prjnum`;
    `echo ' 0  $HOME_DIR' >| $HOME_DIR/.dirstack/dirstack$cur_prjnum`;
}


# Add new entry to online table
push @online_table, "$cur_prjnum,$cur_tty";


# Replace project table with updated online table
open(FF,">$HOME_DIR/.dirstack/prjtable.txt") || die "cant open file\n";
print FF $_."\n" for (@online_table);
close(FF);


# Output current project number
print $cur_prjnum;



###########################################################
####   Subroutines                      ###################
###########################################################

sub isMember {
    my ($element, $ref) = @_;
    my $result = 0;
    for (@$ref) {
       $result = 1 if ($element == $_ );
    }
    return($result);
}


sub GetPnum {

    return (1) if (@_ == 0);   

    my @p_nums = map { @a = split(",", $_); $a[0] } @_;

    my %REC = map { $_ => 1 } @p_nums;

    for ( my $i=1; $i <= max(@p_nums)+1; $i++ ) {
        if (not defined $REC{$i}) {
            return($i);
        }
    }
}

sub max {
    my @tmp = sort { $a <=> $b } @_;
    return $tmp[$#tmp];
}

